# Generated by Django 5.2.7 on 2025-11-09 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the conversation', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is active (soft delete)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this conversation session', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Session',
                'verbose_name_plural': 'AI Chat Sessions',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', help_text='Role of the message sender (user, assistant, or system)', max_length=20)),
                ('content', models.TextField(help_text='The actual message content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Processing status of the AI request', max_length=20)),
                ('message', models.JSONField(blank=True, help_text='Legacy JSON field for message data (deprecated)', null=True)),
                ('response', models.JSONField(blank=True, help_text='Legacy JSON field for response data (deprecated)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(help_text='Chat session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.aichatsession')),
                ('user', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request',
                'verbose_name_plural': 'AI Requests',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['user', 'is_active', '-updated_at'], name='core_aichat_user_id_4d6865_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['-created_at'], name='core_aichat_created_d88597_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['session', 'created_at'], name='core_airequ_session_fb1ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['user', 'created_at'], name='core_airequ_user_id_4e5ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['status'], name='core_airequ_status_b5e7d5_idx'),
        ),
    ]
