# Generated by Django 5.2.7 on 2025-11-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
