name: Custom Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: read
      contents: read
      actions: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install openai PyGithub

      - name: Run migrations and collect static files
        run: |
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Run Custom Code Review
        run: |
          python review.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_PR_ID: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
