name: Run Django Tests with Coverage

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: read
      contents: read
      actions: write

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pylint django djangorestframework pytest-django requests django-cors-headers pyzbar opencv-python numpy python-dotenv openai
        sudo apt-get update -y
        sudo apt-get install -y libzbar-dev

    - name: Set DJANGO_SETTINGS_MODULE environment variable
      run: echo "DJANGO_SETTINGS_MODULE=mysite.settings" >> $GITHUB_ENV

    - name: Run migrations
      run: |
           python manage.py makemigrations
           python manage.py migrate --noinput

    - name: Collect static files
      run: python manage.py collectstatic --noinput

    - name: Run linting with coverage
      run: |
            python -m pylint core || true

    - name: Run tests with coverage (Console (asked for in sprint requirements) and XML report)
      run: pytest --cov=. --cov-report=term --cov-report=xml:coverage.xml --cov-fail-under=80

    - name: Post coverage comment using pytest-coverage-comment
      uses: MishaKav/pytest-coverage-comment@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pytest-xml-coverage-path: coverage.xml
